export function createUserSettingsShim() {
  return {
    dateFormattingInfo: {
      amDesignator: 'AM',
      abbreviatedDayNames: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
      abbreviatedMonthGenitiveNames: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
      abbreviatedMonthNames: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
      calendarWeekRule: 0,
      calendar: { minSupportedDateTime: '/Date(-62135568000000)/', maxSupportedDateTime: '/Date(253402300800000)/' },
      dateSeparator: '/',
      dayNames: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
      firstDayOfWeek: 0,
      fullDateTimePattern: 'dddd, MMMM d, yyyy h:mm:ss tt',
      longDatePattern: 'dddd, MMMM d, yyyy',
      longTimePattern: 'h:mm:ss tt',
      monthDayPattern: 'MMMM dd',
      monthGenitiveNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
      monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
      pmDesignator: 'PM',
      shortDatePattern: 'M/d/yyyy',
      shortTimePattern: 'h:mm tt',
      sortableDateTimePattern: "yyyy'-'MM'-'dd'T'HH':'mm':'ss",
      timeSeparator: ':',
      universalSortableDateTimePattern: "yyyy'-'MM'-'dd HH':'mm':'ss'Z'",
      yearMonthPattern: 'MMMM yyyy',
    },
    isRTL: false,
    languageId: 1033,
    numberFormattingInfo: {
      currencyDecimalDigits: 2,
      currencyDecimalSeparator: '.',
      currencyGroupSeparator: ',',
      currencyGroupSizes: [3],
      currencyNegativePattern: 0,
      currencyPositivePattern: 0,
      currencySymbol: '$',
      nanSymbol: 'NaN',
      nativeDigits: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'],
      negativeInfinitySymbol: '-Infinity',
      negativeSign: '-',
      numberDecimalDigits: 2,
      numberDecimalSeparator: '.',
      numberGroupSeparator: ',',
      numberGroupSizes: [3],
      numberNegativePattern: 1,
      percentDecimalDigits: 2,
      percentDecimalSeparator: '.',
      percentGroupSeparator: ',',
      percentGroupSizes: [3],
      percentNegativePattern: 0,
      percentPositivePattern: 0,
      percentSymbol: '%',
      perMilleSymbol: '\u2030',
      positiveInfinitySymbol: 'Infinity',
      positiveSign: '+',
    },
    securityRoles: ['system-administrator'],
    userId: '{00000000-0000-0000-0000-000000000001}',
    userName: 'Harness User',
    getTimeZoneOffsetMinutes(_date?: Date): number {
      return new Date().getTimezoneOffset() * -1;
    },
  };
}
